---
- hosts: localhost
  become: false

# ////////////////////////////////////////////////////////////////////////////////////////
#  VARIABLES
# ////////////////////////////////////////////////////////////////////////////////////////
  vars_files:
  - "../vars/cluster_vars.yaml"

  vars:
 
 
# ////////////////////////////////////////////////////////////////////////////////////////
#  ENVIRONMENT VARIABLES
# ////////////////////////////////////////////////////////////////////////////////////////
  environment:
    HOSTIP: "{{ inventory_hostname }}"

# ////////////////////////////////////////////////////////////////////////////////////////
#  TASKS
# ////////////////////////////////////////////////////////////////////////////////////////
  tasks:

# ////////////////////////////////////////////////////////////////////////////////////////
#  GRAB ACCOUNTS
# //////////////////////////////////////////////////////////////////////////////////////// 

  # DEPLOY //////////////////////////////////////////////////////////////////////
    - name: Run Script for {{ inventory_hostname }} Accounts JSON
      shell:
      args:
        executable: /usr/bin/bash
        cmd: bash deploy.sh
        chdir: ./
      register: "{{ inventory_hostname }}-accounts"
      # when: (destroy == "false") and (provisioner == "terraform")
    # - debug:
    #     var: results.stdout
 